name: Feature request
description: Propose a feature
title: "feat: "
labels: ["enhancement"]
body:
  - type: textarea
    id: proposal
    attributes: {label: Proposal}
    validations: {required: true}
